[client]
showSidebarNavigation = false

[server]
enableStaticServing = false

[theme]
primaryColor="#410099"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#EFEFEF"
textColor="#141309"
font="sans serif"